name: E2E CI
on:
  push:
    paths:
      - '.github/workflows/e2e-ci.yml'
      - 'web/**'
      - 'server/**'
      - 'e2e/**'
  pull_request:
    paths:
      - 'web/**'
      - 'server/**'
      - 'e2e/**'
jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: |
          cd server
          yarn install
      - name: Build server
        run: |
          cd server
          yarn build
      - name: Save server build
        uses: actions/upload-artifact@v2
        with:
          name: server-build
          if-no-files-found: error
          path: server/build
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: |
          cd web
          yarn install
      - name: Build frontend
        run: |
          cd web
          yarn build
      - name: Save web build
        uses: actions/upload-artifact@v2
        with:
          name: web-build
          if-no-files-found: error
          path: web/build
  end-to-end-test:
    runs-on: ubuntu-latest
    needs: [build-server, build-web]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Get server build
        uses: actions/download-artifact@v2
        with:
          name: server-build
          path: server/build
      - name: Get web build
        uses: actions/download-artifact@v2
        with:
          name: web-build
          path: web/build
      - name: Install Server dependencies
        run: |
          cd server
          yarn install
      - name: Install Web dependencies
        run: |
          cd web
          yarn install
      - name: Install E2E dependencies
        run: |
          cd e2e
          yarn install
      - name: Run E2E tests
        uses: cypress-io/github-action@v4
        with:
          install: false
          start: yarn serve:build
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
          record: true
          working-directory: e2e
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}