name: E2E CI
on:
  push:
    paths:
      - 'web/**'
      - 'server/**'
      - 'e2e/**'
  pull_request:
    paths:
      - 'web/**'
      - 'server/**'
      - 'e2e/**'
jobs:
  end-to-end-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Web dependencies
        run: |
          cd web
          yarn install
      - name: Install Server dependencies
        run: |
          cd server
          yarn install
      - name: Install E2E dependencies
        run: |
          cd e2e
          yarn install
      - name: Run E2E tests
        run: |
          cd e2e
          yarn run test:serve